export const tags = [
  'Animal Care',
  'Art',
  'Board Games',
  'Comedy',
  'Coding',
  'Cooking',
  'Cycling',
  'Esports',
  'Entrepreneurship',
  'Fitness',
  'Football',
  'Gaming',
  'Hiking',
  'Investing',
  'Mental Health',
  'Movies',
  'Music',
  'Photography',
  'Public Speaking',
  'Reading',
  'Study Groups',
  'Sustainability',
  'Yoga'
]; 