import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400","700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Loaf Life",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body 
      className={'${robotoSans.variable} ${robotoMono.variable} antialiased'}>
        {children}
      </body>
    </html>
  );
}
