/**
 * BottomNav.jsx
 * Bottom sticky navbar with clickable links to navigate between main app sections.
 *
 * Generated by ChatGPT o4-mini-high.
 *
 * @author Natalia Arseniuk
 * @author Brady Duval
 * @author https://chatgpt.com/
 *
 * @function BottomNav
 * @description Renders a fixed bottom navigation bar with icons for Home, Add,
 *              Map, and Profile pages, highlighting the active route.
 */

'use client'

import Link from 'next/link' // Next.js Link for client-side navigation
import { usePathname } from 'next/navigation' // Hook to retrieve current pathname
import {
  HomeIcon,
  PlusCircleIcon,
  MapIcon,
  UserIcon,
} from '@heroicons/react/24/outline' // Heroicons outlines for nav icons

export default function BottomNav() {
  const path = usePathname(); // Get current route path to determine active icon

  // Navigation items configuration: destination route, icon component, and title
  const items = [
    { href: '/main-feed-page', icon: HomeIcon, title: 'Home' },
    { href: '/add-form', icon: PlusCircleIcon, title: 'Add' },
    { href: '/map-page', icon: MapIcon, title: 'Map' },
    { href: '/profile', icon: UserIcon, title: 'You' },
  ]

  return (
    // Fixed bottom position, full width, styled with app colors and border
    <nav className="fixed bottom-0 left-0 w-full bg-[#F5E3C6] border-3 border-[#D1905A]">
      <div className="max-w-md mx-auto flex justify-around">
        {items.map(({ href, icon: Icon, title }) => {
          const active = path === href; // Determine if this item is the current route
          return (
            <Link
              key={href}
              href={href}
              className="relative flex-1 flex justify-center items-center py-2"
              aria-label={title} // Accessibility label
              title={title}      // Tooltip text
            >
              {/* Render the icon, changing color if active */}
              <Icon
                className={`h-8 w-8 transition-colors ${active
                    ? 'text-[#639751]'                      // Active color
                    : 'text-[#8B4C24] hover:text-[#639751]' // Inactive and hover color
                  }`}
              />
            </Link>
          )
        })}
      </div>
    </nav>
  )
}
