/**
 * BottomNav.jsx
 * Bottom sticky navbar with clickable links
 * 
 * Generated by ChatGPT o4-mini-high.
 * 
 * @author Natalia Arseniuk
 * @author Brady Duval
 * 
 * @author https://chatgpt.com/
 */

'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import {
  HomeIcon,
  PlusCircleIcon,
  MapIcon,
  UserIcon,
} from '@heroicons/react/24/outline'

export default function BottomNav() {
  const path = usePathname()

  const items = [
    { href: '/main-feed-page', icon: HomeIcon,  title: 'Home' },
    { href: '/add-form',       icon: PlusCircleIcon, title: 'Add' },
    { href: '/map-page',       icon: MapIcon,  title: 'Map' },
    { href: '/profile',        icon: UserIcon, title: 'You' },
  ]

  return (
    <nav className="fixed bottom-0 left-0 w-full bg-[#F5E3C6] border-3 border-[#D1905A]">
      <div className="max-w-md mx-auto flex justify-around">
        {items.map(({ href, icon: Icon, title }) => {
          const active = path === href
          return (
            <Link
              key={href}
              href={href}
              className="relative flex-1 flex justify-center items-center py-2"
              aria-label={title}
              title={title}
            >
              <Icon
                className={`h-8 w-8 transition-colors ${
                  active ? 'text-[#639751]' : 'text-[#8B4C24] hover:text-[#639751]'
                }`}
              />
            </Link>
          )
        })}
      </div>
    </nav>
  )
}
