/**
 * HamburgerMenu.jsx
 * Loaf Life – Renders a dropdown hamburger menu with links to the profile, About Us, and logout action.
 *
 * Generated by ChatGPT o4-mini-high.
 *
 * @author Brady Duval
 * @author Conner Ponton
 * @author https://chatgpt.com/
 *
 * @function HamburgerDropdown
 * @description Displays a hamburger icon that toggles a dropdown menu with navigation links and logout.
 *
 * @function handleClickOutside
 * @description Closes the dropdown if a click occurs outside its container.
 *
 * @function logout
 * @description Signs the user out via Supabase and reloads the page.
 */

'use client'

import { clientDB } from '@/supabaseClient';
import { useState, useRef, useEffect } from "react"
import { Bars3Icon } from "@heroicons/react/24/outline"
import Link from "next/link"

export default function HamburgerDropdown() {
    // Dropdown open state
    const [open, setOpen] = useState(false);
    // Ref to the dropdown container for outside click detection
    const ref = useRef(null);

    useEffect(() => {
        /**
         * handleClickOutside
         *
         * @function handleClickOutside
         * @param {MouseEvent} e - The mousedown event.
         * @description If click is outside the ref element, close the dropdown.
         */
        function handleClickOutside(e) {
            if (ref.current && !ref.current.contains(e.target)) {
                setOpen(false); // Close menu on outside click
            }
        }
        document.addEventListener("mousedown", handleClickOutside)
        return () => document.removeEventListener("mousedown", handleClickOutside)
    }, [])

    return (
        <div ref={ref} className="relative">
            {/* Hamburger button toggles menu open/close */}
            <button
                onClick={() => setOpen(o => !o)}
                className="
            p-2 rounded-md
            hover:bg-[#D1905A]/20
            focus:outline-none focus:ring-2 focus:ring-[#8B4C24]
            transition
            "
            >
                <Bars3Icon className="h-10 w-10 text-[#8B4C24]" /> {/* Hamburger icon */}
            </button>

            {open && (
                <div className="absolute right-0 mt-2 w-24 bg-white border border-[#D1905A] rounded-lg shadow-lg overflow-hidden z-200 
                        transition ease-out duration-150">
                    <ul className="flex flex-col">
                        <li>
                            {/* Link to profile page */}
                            <Link
                                href="/profile"
                                className="block px-4 py-3 text-sm text-[#8B4C24] hover:bg-[#F5E3C6] transition-colors"
                            >
                                Profile
                            </Link>
                        </li>
                        <li>
                            <Link
                                href="/about-page"
                                className="block px-4 py-3 text-sm text-[#8B4C24] hover:bg-[#F5E3C6] transition-colors"
                            >
                                About Us
                            </Link>
                        </li>
                        <li>
                            {/* Logout button triggers Supabase signOut and reload */}
                            <button
                                className="w-full text-left block px-4 py-3 text-sm text-[#8B4C24] hover:bg-[#F5E3C6] transition-colors"
                                onClick={async function logout() { await clientDB.auth.signOut(); window.location.reload(); }}
                            >
                                Logout
                            </button>
                        </li>
                    </ul>
                </div>
            )}
        </div>
    )
}
