/**
 * HamburgerMenu.jsx
 * Loaf Life – renders a dropdown hamburger menu with links to the profile, settings, and logout.
 * 
 * Generated by ChatGPT o4-mini-high.
 * 
 * @author Brady Duval
 * @author https://chatgpt.com/
 */

'use client'

import { useState, useRef, useEffect } from "react"
import { Bars3Icon } from "@heroicons/react/24/outline"
import Link from "next/link"

export default function HamburgerDropdown() {
    const [open, setOpen] = useState(false)
    const ref = useRef(null)

    useEffect(() => {
        function handleClickOutside(e) {
            if (ref.current && !ref.current.contains(e.target)) {
                setOpen(false)
            }
        }
        document.addEventListener("mousedown", handleClickOutside)
        return () => document.removeEventListener("mousedown", handleClickOutside)
    }, [])

    return (
        <div ref={ref} className="relative">
            {/* hit area and focus ring on hamburger*/}
            <button
                onClick={() => setOpen(o => !o)}
                className="
            p-2 rounded-md
            hover:bg-[#D1905A]/20
            focus:outline-none focus:ring-2 focus:ring-[#8B4C24]
            transition
            "
            >
                <Bars3Icon className="h-10 w-10 text-[#8B4C24]" />
            </button>

            {open && (
                <div className="absolute right-0 mt-2 w-24 bg-white border border-[#D1905A] rounded-lg shadow-lg overflow-hidden z-50 
                        transition ease-out duration-150">
                    <ul className="flex flex-col">
                        <li>
                            <Link
                                href="/profile"
                                className="block px-4 py-3 text-sm text-[#8B4C24] hover:bg-[#F5E3C6] transition-colors"
                            >
                                Profile
                            </Link>
                        </li>
                        <li>
                            <Link
                                href="/settings"
                                className="block px-4 py-3 text-sm text-[#8B4C24] hover:bg-[#F5E3C6] transition-colors"
                            >
                                Settings
                            </Link>
                        </li>
                        <li>
                            <button
                                className="w-full text-left block px-4 py-3 text-sm text-[#8B4C24] hover:bg-[#F5E3C6] transition-colors"
                            >
                                Logout
                            </button>
                        </li>
                    </ul>
                </div>
            )}
        </div>
    )
}
