/**
 * SortDropdown.jsx
 * Loaf Life – renders a dropdown menus for sorting / filtering.
 * 
 * Refractored by Brady from code
 * generated by ChatGPT o4-mini-high.
 * 
 * @author https://chatgpt.com/
 */

import { useState, useRef, useEffect } from "react"
import { ChevronDownIcon } from "@heroicons/react/24/outline"

export default function SortDropdown({ label, options, onChange }) {
  const [open, setOpen] = useState(false)
  const ref = useRef(null)

  useEffect(() => {
    function handleClickOutside(e) {
      if (ref.current && !ref.current.contains(e.target)) {
        setOpen(false)
      }
    }
    document.addEventListener("mousedown", handleClickOutside)
    return () => document.removeEventListener("mousedown", handleClickOutside)
  }, [])

  return (
    <div ref={ref} className="relative inline-block text-left">
      <button
        onClick={() => setOpen(o => !o)}
        className="flex items-center space-x-1 text-sm font-medium text-[#8B4C24] hover:text-[#639751] focus:outline-none"
      >
        <span>{label}</span>
        <ChevronDownIcon className="h-4 w-4" />
      </button>

      {open && (
        <ul className="absolute mt-1 w-24 bg-white border border-[#D1905A] rounded-md shadow-lg z-20 overflow-hidden">
        {options.map(opt => (
          <li key={opt}>
            <button
              onClick={() => {
                onChange(opt)
                setOpen(false)
              }}
              className={`
                block w-full text-left px-4 py-2 text-sm
                ${opt === label
                  ? "bg-[#639751] text-white font-semibold"
                  : "text-[#8B4C24] hover:bg-[#F5E3C6]"
                }
              `}
            >
              {opt}
            </button>
          </li>
        ))}
      </ul>      
      )}
    </div>
  )
}
